stages: # List of stages for jobs, and their order of execution
  - build
  - internal-pub
  - notify

variables:
  GOPROXY: https://goproxy.cn,direct
  GOPATH: "$CI_PROJECT_DIR/.go"
  GOBIN: "$CI_PROJECT_DIR/.go/bin"

compose-build-saas:
  image: iseki0/go-deno:latest
  stage: build
  artifacts:
    expire_in: 3 day
    paths:
      - out/murphysec-saas-linux-amd64
      - out/murphysec-saas-windows-amd64.exe
      - out/murphysec-saas-darwin-amd64
      - out/murphysec-saas-linux-amd64.sha256
      - out/murphysec-saas-windows-amd64.exe.sha256
      - out/murphysec-saas-darwin-amd64.sha256
  cache:
    key: cli-build-cache-0041
    paths:
      - .go/pkg/mod/
  before_script:
    - mkdir -p .go
  script:
    - GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-s -w' -o out/murphysec-saas-linux-amd64
    - GOOS=windows GOARCH=amd64 go build -trimpath -ldflags '-s -w' -o out/murphysec-saas-windows-amd64.exe
    - GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags '-s -w' -o out/murphysec-saas-darwin-amd64
    - sha256sum out/murphysec-saas-linux-amd64 | cut -d ' ' -f 1 > out/murphysec-saas-linux-amd64.sha256
    - sha256sum out/murphysec-saas-darwin-amd64 | cut -d ' ' -f 1 > out/murphysec-saas-darwin-amd64.sha256
    - sha256sum out/murphysec-saas-windows-amd64.exe | cut -d ' ' -f 1 > out/murphysec-saas-windows-amd64.exe.sha256
    - sha256sum out/*

compose-build:
  image: iseki0/go-deno:latest
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - out/murphysec-linux-amd64
      - out/murphysec-windows-amd64.exe
      - out/murphysec-darwin-amd64
      - out/murphysec-linux-amd64.sha256
      - out/murphysec-windows-amd64.exe.sha256
      - out/murphysec-darwin-amd64.sha256
  cache:
    key: cli-build-cache-0041
    paths:
      - .go/pkg/mod/
  before_script:
    - mkdir -p .go
  script:
    - GOOS=linux GOARCH=amd64 go build -tags pro -trimpath -ldflags '-s -w' -o out/murphysec-linux-amd64
    - GOOS=windows GOARCH=amd64 go build -tags pro -trimpath -ldflags '-s -w' -o out/murphysec-windows-amd64.exe
    - GOOS=darwin GOARCH=amd64 go build -tags pro -trimpath -ldflags '-s -w' -o out/murphysec-darwin-amd64
    - sha256sum out/murphysec-linux-amd64 | cut -d ' ' -f 1 > out/murphysec-linux-amd64.sha256
    - sha256sum out/murphysec-darwin-amd64 | cut -d ' ' -f 1 > out/murphysec-darwin-amd64.sha256
    - sha256sum out/murphysec-windows-amd64.exe | cut -d ' ' -f 1 > out/murphysec-windows-amd64.exe.sha256
    - sha256sum out/*

internal-cos-upload:
  image: iseki0/cos-uploader:v1.1.2
  stage: internal-pub
  script:
    - cd out
    - cos-uploader --local murphysec-linux-amd64 --remote /client/$CI_BUILD_REF_NAME/murphysec-linux-amd64
    - cos-uploader --local murphysec-darwin-amd64 --remote /client/$CI_BUILD_REF_NAME/murphysec-darwin-amd64
    - cos-uploader --local murphysec-windows-amd64.exe --remote /client/$CI_BUILD_REF_NAME/murphysec-windows-amd64.exe
    - cos-uploader --local murphysec-saas-linux-amd64 --remote /client/$CI_BUILD_REF_NAME/murphysec-saas-linux-amd64
    - cos-uploader --local murphysec-saas-darwin-amd64 --remote /client/$CI_BUILD_REF_NAME/murphysec-saas-darwin-amd64
    - cos-uploader --local murphysec-saas-windows-amd64.exe --remote /client/$CI_BUILD_REF_NAME/murphysec-saas-windows-amd64.exe
    - mkdir zipfiles
    - zip zipfiles/pro.zip murphysec-linux-amd64* murphysec-darwin-amd64* murphysec-windows-amd64.exe*
    - cos-uploader --local zipfiles/pro.zip --remote /client/$CI_BUILD_REF_NAME/pro.zip
    - zip zipfiles/saas.zip murphysec-saas-linux-amd64* murphysec-saas-darwin-amd64* murphysec-saas-windows-amd64.exe*
    - cos-uploader --local zipfiles/saas.zip --remote /client/$CI_BUILD_REF_NAME/saas.zip

lark-notify:
  image: denoland/deno
  stage: notify
  script:
    - deno run --allow-all lark-push.js
