stages: # List of stages for jobs, and their order of execution
  - build
  - internal-pub
  - notify

variables:
  GOPROXY: https://goproxy.cn,direct
  GOPATH: "$CI_PROJECT_DIR/.go"
  GOBIN: "$CI_PROJECT_DIR/.go/bin"
  CGO_ENABLED: '0'

compose-build:
  image: golang:1.19.1-bullseye
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - out/*
  cache:
    key: cli-build-cache-1223
    paths:
      - .go/pkg/mod/
  before_script:
    - mkdir -p .go
  script:
    - GOOS=linux GOARCH=amd64 go build -tags pro -trimpath -ldflags '-s -w -buildid=' -o out/murphysec-linux-amd64
    - GOOS=windows GOARCH=amd64 go build -tags pro -trimpath -ldflags '-s -w -buildid=' -o out/murphysec-windows-amd64.exe
    - GOOS=darwin GOARCH=amd64 go build -tags pro -trimpath -ldflags '-s -w -buildid=' -o out/murphysec-darwin-amd64
    - sha256sum out/murphysec-linux-amd64 | cut -d ' ' -f 1 > out/murphysec-linux-amd64.sha256
    - sha256sum out/murphysec-darwin-amd64 | cut -d ' ' -f 1 > out/murphysec-darwin-amd64.sha256
    - sha256sum out/murphysec-windows-amd64.exe | cut -d ' ' -f 1 > out/murphysec-windows-amd64.exe.sha256
    - GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-s -w -buildid=' -o out/murphysec-saas-linux-amd64
    - GOOS=windows GOARCH=amd64 go build -trimpath -ldflags '-s -w -buildid=' -o out/murphysec-saas-windows-amd64.exe
    - GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags '-s -w -buildid=' -o out/murphysec-saas-darwin-amd64
    - sha256sum out/murphysec-saas-linux-amd64 | cut -d ' ' -f 1 > out/murphysec-saas-linux-amd64.sha256
    - sha256sum out/murphysec-saas-darwin-amd64 | cut -d ' ' -f 1 > out/murphysec-saas-darwin-amd64.sha256
    - sha256sum out/murphysec-saas-windows-amd64.exe | cut -d ' ' -f 1 > out/murphysec-saas-windows-amd64.exe.sha256
    - sha256sum out/*

internal-cos-upload:
  image: iseki0/cos-uploader:v1.1.2
  stage: internal-pub
  script:
    - chmod 755 ./ci/pack.sh && ./ci/pack.sh

lark-notify:
  image: denoland/deno
  stage: notify
  script:
    - deno run --allow-all lark-push.js
