stages: # List of stages for jobs, and their order of execution
  - build
  - internal-pub
  - notify

variables:
  GOPROXY: https://goproxy.cn,direct
  GOPATH: "$CI_PROJECT_DIR/.go"
  GOBIN: "$CI_PROJECT_DIR/.go/bin"
  CGO_ENABLED: '0'
  DENO_DIR: "$CI_PROJECT_DIR/.deno"

compose-build:
  image: golang:1.19.2-bullseye
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - out/bin/*
  cache:
    key: cli-build-cache-1223
    paths:
      - .go/pkg/mod/
  before_script:
    - mkdir -p .go
  script:
    - chmod +x ./ci/mp-build.sh && ./ci/mp-build.sh
    - sha256sum out/bin/*

internal-cos-upload:
  image: iseki0/cos-uploader:v1.1.3
  stage: internal-pub
  artifacts:
    expire_in: 1 day
    paths:
      - out/zip/*
  script:
    - chmod 755 ./ci/pack.sh && ./ci/pack.sh

lark-notify:
  image: denoland/deno
  stage: notify
  cache:
    key: cli-deno-cache-1223
    paths:
      - .deno
  script:
    - deno run --allow-all lark-push.ts
