name: Build

on:
  push:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/build.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, darwin ]
        goarch: [ amd64, arm64 ]
        include:
          - goos: windows
            goarch: amd64
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: '0'
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Download dependencies
        run: go mod download

      - name: Build without tag
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: go build -v -ldflags "-s -w -buildid=" -trimpath -o out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/murphy

      - name: Build with tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: go build -v -ldflags "-s -w -X github.com/murphysecurity/murphysec/infra/buildinfo.version=$GITHUB_REF_NAME -buildid=" -trimpath -o out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/murphy

      - name: Rename for Windows
        if: matrix.goos == 'windows'
        run: mv out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }} out/murphysec-${{ matrix.goos }}-${{ matrix.goarch }}.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: murphysec-${{ matrix.goos }}-${{ matrix.goarch }}
          path: out/*

  merge:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: murphysec-linux-amd64
      - uses: actions/download-artifact@v3
        with:
          name: murphysec-linux-arm64
      - uses: actions/download-artifact@v3
        with:
          name: murphysec-windows-amd64
      - uses: actions/download-artifact@v3
        with:
          name: murphysec-darwin-arm64
      - uses: actions/download-artifact@v3
        with:
          name: murphysec-darwin-amd64
      - run: ls -alh
        if: always()
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./murphysec-*
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3

      - name: Show files
        run: |
          pwd
          find

      - name: Calc hash
        run: |
          mkdir -p out
          cp ./murphysec-linux-amd64/murphysec-linux-amd64 ./out/
          cp ./murphysec-windows-amd64/murphysec-windows-amd64.exe ./out/
          cp ./murphysec-darwin-amd64/murphysec-darwin-amd64 ./out/
          cp ./murphysec-darwin-arm64/murphysec-darwin-arm64 ./out
          cp ./murphysec-linux-arm64/murphysec-linux-arm64 ./out
          cd out
          sha256sum * > sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/*
          draft: true
