name: Test

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  DEFAULT_MAVEN_REPO: https://repo1.maven.org/maven2/
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: '0'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
          check-latest: true
          cache: true

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Set up gotestfmt
        run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Run tests
        run: |
          set -euo pipefail
          go generate ./...
          go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt 
